spring:
  datasource:
    url: jdbc:mysql://localhost:3306/memberdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: yunjin
    password: rkddkwl
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  name: memberservice